### ISSUE TITLE
Resources$NotFoundException

### ISSUE THREAD

**Issue by pop1030123** [yoojia/FireEye#5]
version:com.github.yoojia:fire-eye:1.2@aar
Exception:
android.content.res.Resources$NotFoundException: String resource ID #0x7f0b0383
	at android.content.res.Resources.getText(Resources.java:1123)
	at android.content.res.Resources.getString(Resources.java:1217)
	at com.github.yoojia.fireeye.validators.ValidatorFactory.build(Unknown Source)
	at com.github.yoojia.fireeye.FireEye.add(Unknown Source)

**Comment by hslls** [comment]
@pop1030123 解决了吗？类似的问题

三星Galaxy Note II
4.1.2
android.content.res.Resources$NotFoundException: String resource ID #0x7f0b0298

**Comment by pop1030123** [comment]
@hslls 我升级到了2.0版本，暂时未发现类似问题 。
